### ISSUE TITLE
Playtest- Canal Sauna Wood and Bottles Respawn Too Fast

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#1038]
Beer crate no longer spawns bottles in world, but after grabbing wood + clearing bottles, hitting the sauna for a bit, returning outside the wood has doubled and beer crate is almost full again.

**Comment by Nextej** [comment]
Feels like the wood shouldn't respawn at all and not spawn in the first place, since it's player's, it should be player's responsibility to get some firewood to it, could also encourage figuring out how to make firewood. The storage itself should be a safe place to leave firewood without a fear of it getting removed.

**Comment by Zuntti** [comment]
Doesn't happen to me. Maybe build only issue? They shouldn't respawn at all
