### ISSUE TITLE
Feature: Difficulty levels

### ISSUE THREAD

**Issue by Zuntti** [loiste-interactive/Obenseuer-Issues#1144]
Here are two ideas how it could work
1. One difficulty setting which would adjust all settings
2. Each has its own setting
- One for needs
- One for addictions
- One for the prices of renovations
- More??

You can choose the level of difficulty when creating a character but maybe you could also change it in the middle of the game?

Levels of difficulty
- Easy (Maybe cuts all needs in half? Maybe even remove addictions?)
- Default
Need a harder difficulty level than default or maybe relaxing mode without needs or addictions?

Put ideas here on how the difficulty levels should work

**Comment by Nextej** [comment]
I think the default settings should be the most balanced and intended way to play, so pretty much how the game is now, except for addiction rates that were either silently reduced between .15 and .16 or are bugged, since currently addiction needs come up rarely, addictions are gone within 5 days from the start and generally you're getting rid of them effortlessly. And back on .15 I thougth they were too easy to get rid off already, see #908 and #946 from .15. So for this one at most, check whether the addictions aren't bugged or whether they were intentionally reduced in .16.

I would solve the difficulty levels by having a bunch of checkmarks to associated level of difficulty. Also with small highlightable explanatory hints like "The most balanced difficulty" or "Default depression gain is disabled, only items that purposely have negative mental health effects will increase depression"
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9206be6c-4665-46b1-9bf6-eab6384c67ad)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/66950024-6830-4f57-86f4-3f6e37b03ce8)

For harder settings, I'd love to have bigger save restrictions: unability to create new savefiles, unability to load autosave, being able to restart whole day (game would need to create savefiles at a set hour each day and give the player ability to revert to any day in the past).

**Comment by Nextej** [comment]
> You can choose the level of difficulty when creating a character but maybe you could also change it in the middle of the game?

Perhaps you could change settings mid-game on Relaxing mode, but Default would have them set permanently?

**Comment by Oskutin** [comment]
Brutal mode should just remove player's save upon death.

**Comment by Nextej** [comment]
"Creative" mode that allows to start with things like: all recipes unlocked, all blueprints unlocked, furniture is for free, all upgrades unlocked (not related to contractor level or requirement of other upgrades), all upgrades are already installed, basement is already unlocked.

**Comment by greensalt99** [comment]
leave addictions on all diff levels, this is main part of game. i have lost addictions and game sort of lost its taste - became bland :D

spoiling levels could be tied to difficulty, but good game should not have difficulties. Mechanics should be fun not annoying.
agree on renovation cost but, i suggested secondary mechanics to counter that
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1666

changing setting in game is sort of benefit, if you took bad difficulty combo and you dont want to restart game.
not all people like restarting.
