### ISSUE TITLE
Playtesting - sometimes after ending OS-Magazine job, player gets stuck and can't move, reloading helps

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1469]
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13688800/Player.zip)

**Comment by greensalt99** [comment]
ill add my note. when your tiredness is over 90% , my was 97% you get stuck. if 77% you can walk away.
i guess when forced sleeping should kick in (super tiredness)  it does not start because you were working at OS telemarketing. 
Simple fix:
1. after work you start sleeping on table.
2. when you work you get free coffee so your tiredness don't go over 90%
3. when your tiredness reach 90% you cancel your work.

**Comment by Oskutin** [comment]
Fixed
