### ISSUE TITLE
Playtest V 0.3.28 - multiple items spawning ontop of each other

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1607]
a good example of this is in kolhola, i was able to grab 5 disinfectant from the one spawn in hte hallway aswell as multiple items from the cleaning kart upstairs. this was on a new save

**Comment by sashort** [comment]
I've noticed this for a while. I wasn't sure if this is a bug or a feature that needs refinement. These locations are where a new item will spawn there after about a day.

The question is, what happens when there's an item that has previously spawned still sitting there?
Should they both be there, or should the old item be replaced?

If both are supposed to be there, maybe write a function that will calculate where to spawn the item based upon what is already spawned. The function would also have to know how many items have already spawned for that location, and a maximum number of spawned items allowed for that location. If you don't discover this place until in-game weeks without those aspects, you'll have dozens of spawned items for that location strewn all over the place.
