### ISSUE TITLE
Given skill level for planting from seeds and planting from a plant is not the same.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1955]
Might be affected only on fields with gain modifier.

**Comment by Zuntti** [comment]
Probably because the fail chance is different which affects how much you get skill level

**Comment by Nextej** [comment]
the issue is, people who use seeds exclusively barely get any skill gain, people who use produce exclusively level up to 10th level in no time

**Comment by Zuntti** [comment]
Maybe I should decrease how much fail change affects to skill gain when planting

**Comment by Nextej** [comment]
https://discord.com/channels/478514341176672267/522172830758993934/1199306412845695106 my testings of the issue, can't test it properly now with bugged planting of stacked items.

**Comment by Zuntti** [comment]
Those were when you could get only 0.00**0**125 from seeds

**Comment by Nextej** [comment]
so it was changed already?

**Comment by Zuntti** [comment]
Yeah

**Comment by Zuntti** [comment]
Changed values skill gaining values. It also took fail chance directly from the recipe instead of what it's actually after adding other variables such as the player's skill. So now you get a little less level from planting when skill increases and fail chance is smaller, but minimum you get is always (0.001 * skill gain factor * amount)
