### ISSUE TITLE
[Feedback] Player should get mushrooms in prison

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2016]
In prison the player is given, food, water, beer and cigarettes. If the player has mushroom addiction, then they have no way of getting them and their mental health will go down until they kill themself. A simple fix would be to give the player low potency mushrooms that have bad health effects. The player should also be able to ask for a top up of their addiction items (mushrooms, beer, etc).

**Comment by DragonZephyr** [comment]
Its an issue that the prison provides you with anything for your addictions in the first place just because they are able to kill you, Currently the prison does not provide water frequently enough for you which forces one to drink dirty water which costs the player health leading them to death. In my recent playthrough this is what killed me in my maxed out prison sentence of 100 hours despite also having maxed mushroom addictions.
For the mushroom situation the same thing happens, i grab the glowing rat spawn and potential mushrooms from grates and eat them which costs so much health they kill me just to stall for prison time. The glowing rat spawn also felt very intentional to help with my addictions but at 100% addiction you cannot be satiated even if the guard gave you 8 mushroom rollies for the day. (I setup things in the cell in advance of the sentence to survive and even then underestimated how much i needed) Colton has useful trades but is only in one cell either forcing you to play a lockpicking minigame twice on a single lockpick or gambling to be put in the correct cell.

The simplest solution might be having a minimum for mental state and health so that a player can't kill themselves too easily through situations and actually engages with prison instead of loading to an earlier save, the game intentionally writes over both autosaves to make that less appealing but that "trick" only works once on a player until they start saving frequently.

The prison needs to leave a player devastated afterwards so they are discouraged from engaging in criminal activity without having a plan and making the gameplay inside of jail be how to not lose all of your mental state or health which might be engaging compared to taking money as in #1606 or providing the solution of issues partially created by the player and partially the game to drive you to interact with the world.

Handing the player resources for screwing up and being put in jail might be bad as it could lead to intentional prison sentences to create resources rapidly, doing intentional small ammounts of crime to be given free meals and time acceleration of several hours is a good deal and if turning yourself in has any stat advantage of your crime points it gets even better.
Even if you were not to receive rent for your prison time you could go for long crafting queues or accrue debit card money. If the game introduces tempreture and freezing to death it would just be another thing you would need to be handed in prison so that it does not become an immediate reload.

I believe having a hole between the cells so colton can be reached or asking the guard to be switched to the other cell might also be good as discovering a merchant that buys almost anything is great and if instead of giving players bottles of beer they are only given water and bread the issue of the waiting objects checking Mental State Target instead of the current mental state would not be there too as getting drunk is not useful for being able to waste more time which players might attempt. (I atleast did)

The minimums im proposing might also work as soft caps that progressively make it harder for you to lose those 2 stats (or maybe all stats?) while in jail essentially providing modifiers so you can gain less pentalties if you are already very close to 0 this could even be a good lever for having players build up "prison resistence" or inversly can be used to balance prisons to make them harder by having less of a modulator in the players favor either for difficulty levels or for punishing repeat offenders who do not learn. Might be easier to code then catching tons of corner cases for current features and future features aswell by having a ton of checks or a massive dialogue tree to either ask for all these things or be given them.

Also i mean, how do you cut yourself in prison i doubt the guard lets you keep any sharp implement to hurt yourself. With the can opener? That thing does not even spawn half the time im in there unless i reload a save in prison. Even in prisons where you are allowed sharp tools atleast somebody is present to watch you because suicide is just another way to escape prison sentence.

Once its harder to over-abuse the player while in prison having more bad things might also be an option like having the guard wake you up either by accident or intent or being provided better vs worse food depending on if you are likely to escape or how you behave in prison.

**Comment by Taco-Cat1** [comment]
That’s a lot of detail. But if the player doesn’t have mushrooms in their cell then they will die. Even if the player could somehow get a full inventory of beer mushrooms and cigarettes, they don’t sell for too much. A solution for this would be that the player can only ask for addition items (beer mushrooms etc) if they have none in their cell so even taking as much as possible would only result in a few open sewer coins. To fix the health issue the player could ask for some pain killers (maybe with only 1 or 2 pills inside) every other day to keep their health up or if their health is below 25% then they would have it every day until they heal. Prison could also take away 20-40% of the fine the player would have to pay so it’s not just free living.

**Comment by Taco-Cat1** [comment]
Player could also be forced to cough up some cash each day of about 80% of their rent and debit card money could be removed. Also instead of the player being put to sleep when they go into prison, make it only that they are brought to prison while awake. And to get rent and debt card money is already possible and very easy if the player doesn’t have mushroom addiction and other addiction are on the lower end so giving the player mushrooms isn’t that bad.

**Comment by Oskutin** [comment]
i could change the taps to give shroom water

**Comment by Taco-Cat1** [comment]
That’s okay but there should still be a way to regain health so the player doesn’t die from that in long prison sentences.

**Comment by Nextej** [comment]
Realistically the guards would strip you from anything that you could use to cut yourself, so perhaps that should be disabled while in jail?

Perhaps add ability to ask for medicine (painkillers and antidepressants) to be delivered along the food. Alternatively add jail-issued item akin to something like a nicotine patch that will help with surviving addictions.

**Comment by Taco-Cat1** [comment]
To be honest when you have 0 mental health I think the game just lets you cut yourself and bleed to death and I don’t think you need anything (correct me if I’m wrong). Also if shrooms come from a vending machine then I think they are legal. Removing mental health in prison would let the player easily get rid of their addictions by simply not catering for them and letting them go away. You also need the consider that the player can simply walk out of jail with the items in their cell and taking the nicotine patch or other things would let the player never take care of their addictions again. A way to fix this is to let the taps give Sharon water and let the player ask for medication if needed.

**Comment by DragonZephyr** [comment]
The 0 mental health thing isnt reliant on an item but its implied you are hurting yourself with a knife like with borderline disorder and in prison people dont let you kill yourself. You are right you could lose your addictions during pirson but luckily that can be set to 0 during prison stay as its a player stat (the addiction decay). 
I have not had shroom water but if it does not cause health damage people would props rather drink it even if they do no have mush addiction when they do run out of water in prison which was an issue for me. It also will get worse with mental states in prison once the mental health modulation from smoking comes in next version.
Can bottled mushroom water be sold to the gang in Deek C? Maybe its fine though if you end up having more after a prison stay, but the main worry i have is that most people will just escape or reload since that is easier then leaving the game running when you can't accelerate time due to mental health and then breaking out when you are about to die just so burn part of the bounty off. Which is something pretty contrived to have to come up with.

To be fair you can bribe the guard to let you out and erase your crime record but i have not had any success with that. Maybe that could be the end goal of high prison sentence. Just that it would bite itself with any idea of them taking money from you for the prison stay like in #1606 because the penalty might quickly go over what you have with cameras spotting you like in goldshields apartment and most merchants giving you less then the real price of itmes.

My arguement was that having mental health loss slow down as it approaches 0 might just make it play like you would always come up pretty miserable from jail without having died regardless if you escape or not if you are at 1% and get released and immediatley hurt yourself you might still die without a bandage but atleast you would have a chance to heal. Another approach could just be making it so the guard bandages you up when you start cutting yourself since having any addiction at 100 might make the need go up too fast for what you are given. Oskutin was considering a gambling addiction too if the negative effect is mental health then we are back at square 0 where either players need to die in jail or not since i doubt every addiction this game might give can be dealt with in a prison.

Could also be funny though having a duck, a bottle of oslut, a deck of cards to play against yourself and cigars given to you during your prison time and leaving with a couple bottles of shroom water to satify your needs the coming days since the guard does not take any of that.

**Comment by Taco-Cat1** [comment]
What if the player was just given bandages to stop bleeding and is given mushrooms to keep their mental health up. I feel like adding all these extra rules to prison removes from the fun of the game because if one area is just so complicated then the game isn’t fun (in my opinion)

**Comment by DragonZephyr** [comment]
Bandages are a good idea since they also heal a tiny bit of health

**Comment by Taco-Cat1** [comment]
Yeah I think that’s the solution

**Comment by Oskutin** [comment]
Player can now request stuff from guard
