### ISSUE TITLE
{PLAYTESTING} - Whilst in jail with both jail doors closed the guard will re-arrest you for it being open when its not.

### ISSUE THREAD

**Issue by Defence-Cannon** [loiste-interactive/Obenseuer-Issues#2580]
[DaVey_McMulch (2).zip](https://github.com/user-attachments/files/16645762/DaVey_McMulch.2.zip)

**Comment by CVariable** [comment]
i had this happen too. The guard said "hey! why is the jail door open? Stay right there!" despite me only just having been thrown into jail
![grafik](https://github.com/user-attachments/assets/fe244a8a-7563-419a-a136-1d248fbc205e)

**Comment by Pangaron** [comment]
Reocuring on Playtest 0.3.42 V3

Seems to be occurring only in the cell with the hole in the wall (so far). Gave myself in to the officer near OM mart.
Saved just after being taken in the cell (cell with the hole in the wall)
[Slot4.zip](https://github.com/user-attachments/files/17564272/Slot4.zip)
In order to replicate the bug, the guard needs look towards you (seems semi-random), usually running around the cell and towards the bars seem to trigger it, but might need a few reloads. The cell doors are closed the whole time.

Second save after being transferred into the second cell (sometimes the first cell is picked again and the whole ordeal repeats)
[Slot9.zip](https://github.com/user-attachments/files/17564273/Slot9.zip)

[Player - Copy.log](https://github.com/user-attachments/files/17564282/Player.-.Copy.log)

**Comment by Oskutin** [comment]
Likely fixed now
