### ISSUE TITLE
"Remove the obstacle" objective not given/completed locking "Getting a passport" task

### ISSUE THREAD

**Issue by MajorMari** [loiste-interactive/Obenseuer-Issues#769]
"Remove the obstacle" objective was either not given or not completed before completing "Find a route to the bank" objective, leading to  not giving the "Tell Passmore what you found" objective, locking the task from progressing.
I only noticed after trying to talk to Passmore again and have now been reloading and checking multiple movement paths at the trigger area and partially removing the obstacle, but couldn't reproduce the issue again.

**Comment by Oskutin** [comment]
You managed to pass that objective after all?

**Comment by MajorMari** [comment]
With reloading a much older save. I just found another save (from just before the issue happend) and it's not giving me the "Remove the obstacle" obstacle again.

**Comment by MajorMari** [comment]
Reloaded one of the saves that did work earlier, but did now talk to Mike and received the "Letter for Emilie Palmer" task. Now this save also does not give me the "Remove the obstacle" objective.

**Comment by MajorMari** [comment]
I can now reproduce it when reloading a save made after talking to Passmore and obtaining the "Find a route to the bank" objective. Saves made just prior to obtaining the objective still work.

**Comment by CubeOfIce** [comment]
I was never given the "Remove the obstacle" objective either, just the one to find the entrance to the bank, and when I found the entrance- the task locked and I couldn't proceed. I made a ticket for the same issue but closed it when I realized this one's for the same problem.

**Comment by Nextej** [comment]
The objective about telling the Passmore about cleared path is also not checked off, player can repeatedly start "The bank drain cover does not budge" dialogue option (which should check that objective off).
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/539bf7d0-89e7-44b1-b03f-baefa90bdbd7)
There's also a small typo in one of the later lines where it should be "she" instead of "he" when talking about Eliana
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/73623fea-3f58-4dbb-8086-5f9258cabf47)

**Comment by Oskutin** [comment]
This is now potentially fixed
